### ISSUE TITLE
同时监控多个日志 实时输出

### ISSUE THREAD

**Issue by jamesdurant** [weiliang-ms/easyctl#1]
同时监控多个日志 尽量减少修改 整合成一个文件 实时输出

**Comment by weiliang-ms** [comment]
> 同时监控多个日志 尽量减少修改 整合成一个文件 实时输出

- [v0.7.6-alpha](https://github.com/weiliang-ms/easyctl/releases/tag/v0.7.6-alpha) 已经支持 

- [说明文档](https://weiliang-ms.github.io/easyctl/%E8%BF%BD%E8%B8%AA%E6%8C%87%E4%BB%A4%E9%9B%86/01%E5%A4%9A%E4%B8%BB%E6%9C%BA%E6%97%A5%E5%BF%97%E5%AE%9E%E6%97%B6%E8%BF%BD%E8%B8%AA.html)
